### ISSUE TITLE
Sol2 version dependency

### ISSUE THREAD

**Issue by kjmathue** [loud-hound/woofer#163]
Was giving Effil a try. Can the **Sol2** version be specified in the readme/instructions? **Effil** [v1.2-0](https://github.com/effil/effil/releases/tag/v1.2-0) of 20 Sep 2020 doesn't seem to compile with the latest Sol2 [v3.2.2](https://github.com/ThePhD/sol2/releases/tag/v3.2.2) of 04 Oct 2020.

Error:
```
In file included from effil-1.2-0/src/cpp/lua-helpers.cpp:1:
effil-1.2-0/src/cpp/lua-helpers.h:42:12: error: no template named 'pusher'; did you mean 'user'?
    struct pusher<effil::StoredArray> {
           ^~~~~~
           user
sol2-3.2.2/single/include/sol/sol.hpp:6746:9: note: 'user' declared here
        struct user {
               ^
In file included from effil-1.2-0/src/cpp/lua-helpers.cpp:1:
effil-1.2-0/src/cpp/lua-helpers.h:42:12: error: class template specialization of 'user' not in a namespace enclosing 'sol'
    struct pusher<effil::StoredArray> {
           ^
sol2-3.2.2/single/include/sol/sol.hpp:6746:9: note: explicitly specialized declaration is here
        struct user {
               ^
2 errors generated.
```

Looks like '**struct pusher**' needs to change to '**struct unqualified_pusher**' etc. with Sol2 v3.2.2?

**Comment by mihacooper** [comment]
Of course Effil depends on particular version of Sol 2. It's not easy just to recompile Effil with newer Sol cause Sol has made some significant changes (I had tried).

The dependency  not in README but you can use git submodules to compile Effil with right version of Sol2.
